### PR TITLE
Feature. Implement DomainService/batchGetInfo

### PR DESCRIPTION
**Pull request by dpavlotzky**
Hi,

Thanks for starting this library. I've implemented the DomainService/batchGetInfo request.

Kind regards / met vriendelijke groet,
David

### CODE REVIEW

**Comment by Freeaqingme** [comment]
Could you perhaps run go-fmt?

**Comment by dpavlotzky** [comment]
Sure, done!

**Comment by dpavlotzky** [comment]
Ping

**Comment by mpdroog** [comment]
Thank you! Added it to the codebase :)

**Pull request merged**
